[package]
name = "ansible-scaffold"
version = "0.1.0"
authors = ["Sam Schmitt <sam@samschmitt.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"