on: [push]

name: Build

jobs:
  Build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        working-directory: ansible-scaffold
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        working-directory: ansible-scaffold
        with:
          command: build
          args: --release --all-features
